// layouts/error.vue
<template>
  <div class="main">
    <div class="error">
      <Logo404 v-if="error.statusCode === 404" />
      <h1 v-else>{{ $t('error-page.title') }}</h1>
      <p>{{ error.message }}</p>
      <div class="button-group">
        <nuxt-link to="/" class="iconified-button raised-button brand-button">
          {{ $t('error-page.actions.go-home') }}
        </nuxt-link>
        <a
          href="https://discord.gg/EUHuJHt"
          class="iconified-button raised-button"
        >
          {{ $t('error-page.actions.join-discord') }}
        </a>
      </div>
    </div>
  </div>
</template>

<script>
import Logo404 from '~/assets/images/404.svg?inline'

export default {
  components: {
    Logo404,
  },
  layout: 'home',
  props: {
    error: {
      type: Object,
      default() {
        return {
          statusCode: 1000,
          message: this.$t('error-page.defaults.error'),
        }
      },
    },
  },
}
</script>

<style lang="scss" scoped>
.main {
  margin: var(--spacing-card-lg) auto;
  width: calc(100% - 4rem);

  @media screen and (min-width: 800px) {
    width: 600px;
  }
}

.error {
  h1 {
    margin-bottom: 0.25rem;
  }

  svg {
    fill: var(--color-text);
    color: var(--color-text);

    width: 100%;
    height: auto;
  }
}
</style>

// src/routes/__error.svelte
<script context="module" lang="ts">
	export function load({ error, status }) {
		return {
			props: {
				status,
				message: error.message,
			},
		};
	}
</script>

<script lang="ts">
	import { t } from 'svelte-intl-precompile';
	import Logo404 from '$assets/images/logo/404.svg';
	import Button from '$components/elements/Button.svelte';
	import Meta from '$components/utils/Meta.svelte';

	export let status: number;
	export let message = '';
</script>

<Meta
	title={$t('error.status', { values: { status } })}
	description={message || $t('error.message.default')}
/>

<div class="status">
	{#if status === 404}
		<Logo404 width="100%" />
	{:else}
		<h1>{$t('error.status', { values: { status } })}</h1>
	{/if}
</div>

<p>
	{#if message}
		{message}
	{:else if status === 404}
		{$t('error.message.404')}
	{:else}
		{$t('error.message.default')}
	{/if}
</p>

<div class="actions">
	<Button href="/" label={$t('error.actions.home')} color="brand" />
	<Button href="/discord" label={$t('error.actions.discord')} color="raised" newTab={true} />
</div>

<style lang="postcss">
	.status {
		display: flex;
		margin: 2rem 0;
		max-width: 600px;
    font-size: 2rem;
	}

	.actions {
		display: flex;
		grid-gap: 0.5rem;
		flex-wrap: wrap;
	}
</style>
