// pages/moderation.vue
<template>
  <div>
    <Modal ref="modal" header="Moderation Form">
      <div v-if="currentProject !== null" class="moderation-modal">
        <p>
          Both of these fields are optional, but can be used to communicate
          problems with a project's team members. The body supports markdown
          formatting!
        </p>
        <div class="status">
          <span>New project status: </span>
          <Badge
            v-if="currentProject.newStatus === 'approved'"
            color="green"
            :type="currentProject.newStatus"
          />
          <Badge
            v-else-if="
              currentProject.newStatus === 'processing' ||
              currentProject.newStatus === 'unlisted' ||
              currentProject.newStatus === 'archived'
            "
            color="yellow"
            :type="currentProject.newStatus"
          />
          <Badge
            v-else-if="currentProject.newStatus === 'rejected'"
            color="red"
            :type="currentProject.newStatus"
          />
          <Badge v-else color="gray" :type="currentProject.newStatus" />
        </div>
        <input
          v-model="currentProject.moderation_message"
          type="text"
          placeholder="Enter the message..."
        />
        <h3>Body</h3>
        <div class="textarea-wrapper">
          <Chips
            v-model="bodyViewMode"
            class="separator"
            :items="['source', 'preview']"
          />
          <textarea
            v-if="bodyViewMode === 'source'"
            id="body"
            v-model="currentProject.moderation_message_body"
          />
          <div
            v-else
            v-highlightjs
            class="markdown-body preview"
            v-html="$xss($md.render(currentProject.moderation_message_body))"
          ></div>
        </div>
        <div class="buttons">
          <button
            class="iconified-button"
            @click="
              $refs.modal.hide()
              currentProject = null
            "
          >
            <CrossIcon />
            Cancel
          </button>
          <button class="iconified-button brand-button" @click="saveProject">
            <CheckIcon />
            Confirm
          </button>
        </div>
      </div>
    </Modal>
    <div class="normal-page">
      <div class="normal-page__sidebar">
        <aside class="universal-card">
          <h1>Moderation</h1>
          <NavStack>
            <NavStackItem link="" label="All"> </NavStackItem>
            <NavStackItem
              v-for="type in moderationTypes"
              :key="type"
              :link="'?type=' + type"
              :label="$formatProjectType(type) + 's'"
            >
            </NavStackItem>
          </NavStack>
        </aside>
      </div>
      <div class="normal-page__content">
        <div class="projects">
          <ProjectCard
            v-for="project in $route.query.type !== undefined
              ? projects.filter((x) => x.project_type === $route.query.type)
              : projects"
            :id="project.slug || project.id"
            :key="project.id"
            :name="project.title"
            :description="project.description"
            :created-at="project.published"
            :updated-at="project.updated"
            :icon-url="project.icon_url"
            :categories="project.categories"
            :client-side="project.client_side"
            :server-side="project.server_side"
            :type="project.project_type"
            :moderation="true"
          >
            <button
              class="iconified-button"
              @click="setProjectStatus(project, 'approved')"
            >
              <CheckIcon />
              Approve
            </button>
            <button
              class="iconified-button"
              @click="setProjectStatus(project, 'unlisted')"
            >
              <UnlistIcon />
              Unlist
            </button>
            <button
              class="iconified-button"
              @click="setProjectStatus(project, 'rejected')"
            >
              <CrossIcon />
              Reject
            </button>
          </ProjectCard>
        </div>
        <div
          v-if="
            $route.query.type === 'report' || $route.query.type === undefined
          "
          class="reports"
        >
          <div
            v-for="(item, index) in reports"
            :key="index"
            class="card report"
          >
            <div class="info">
              <div class="title">
                <h3>
                  {{ item.item_type }}
                  <a :href="item.url">{{ item.item_id }}</a>
                </h3>
                reported by
                <a :href="`/user/${item.reporter}`">{{ item.reporter }}</a>
              </div>
              <div
                v-highlightjs
                class="markdown-body"
                v-html="$xss($md.render(item.body))"
              />
              <Badge :type="`Marked as ${item.report_type}`" color="yellow" />
            </div>
            <div class="actions">
              <button class="iconified-button" @click="deleteReport(index)">
                <TrashIcon /> Delete report
              </button>
              <span
                v-tooltip="
                  $dayjs(item.created).format(
                    '[Created at] YYYY-MM-DD [at] HH:mm A'
                  )
                "
                class="stat"
              >
                <CalendarIcon />
                Created {{ $dayjs(item.created).fromNow() }}
              </span>
            </div>
          </div>
        </div>
        <div v-if="reports.length === 0 && projects.length === 0" class="error">
          <Security class="icon"></Security>
          <br />
          <span class="text">You are up-to-date!</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import {
  EyeOff as UnlistIcon,
  Check as CheckIcon,
  X as CrossIcon,
  Trash2 as TrashIcon,
  Calendar as CalendarIcon,
} from 'lucide-vue'

import Security from '~/assets/images/illustrations/security.svg?inline'

import Chips from '~/components/ui/Chips'
import ProjectCard from '~/components/ui/ProjectCard'
import Modal from '~/components/ui/Modal'
import Badge from '~/components/ui/Badge'
import NavStack from '~/components/ui/NavStack'
import NavStackItem from '~/components/ui/NavStackItem'

export default {
  name: 'Moderation',
  components: {
    NavStack,
    NavStackItem,
    Chips,
    ProjectCard,
    CheckIcon,
    CrossIcon,
    UnlistIcon,
    Modal,
    Badge,
    Security,
    TrashIcon,
    CalendarIcon,
  },
  async asyncData(data) {
    const [projects, reports] = (
      await Promise.all([
        data.$axios.get(`moderation/projects`, data.$defaultHeaders()),
        data.$axios.get(`report`, data.$defaultHeaders()),
      ])
    ).map((it) => it.data)

    const newReports = await Promise.all(
      reports.map(async (report) => {
        try {
          report.item_id = report.item_id?.replace
            ? report.item_id.replace(/"/g, '')
            : report.item_id
          let url = ''

          if (report.item_type === 'user') {
            const user = (
              await data.$axios.get(
                `user/${report.item_id}`,
                data.$defaultHeaders()
              )
            ).data
            url = `/user/${user.username}`
            report.item_id = user.username
          } else if (report.item_type === 'project') {
            const project = (
              await data.$axios.get(
                `project/${report.item_id}`,
                data.$defaultHeaders()
              )
            ).data
            report.item_id = project.slug || report.item_id
            url = `/${project.project_type}/${report.item_id}`
          } else if (report.item_type === 'version') {
            const version = (
              await data.$axios.get(
                `version/${report.item_id}`,
                data.$defaultHeaders()
              )
            ).data
            const project = (
              await data.$axios.get(
                `project/${version.project_id}`,
                data.$defaultHeaders()
              )
            ).data
            report.item_id = version.version_number || report.item_id
            url = `/${project.project_type}/${
              project.slug || project.id
            }/version/${report.item_id}`
          }

          report.reporter = (
            await data.$axios.get(
              `user/${report.reporter}`,
              data.$defaultHeaders()
            )
          ).data.username

          return {
            ...report,
            moderation_type: 'report',
            url,
          }
        } catch (err) {
          return {
            ...report,
            url: 'error',
            moderation_type: 'report',
          }
        }
      })
    )

    return {
      projects,
      reports: newReports,
    }
  },
  data() {
    return {
      bodyViewMode: 'source',
      currentProject: null,
    }
  },
  head: {
    title: 'Moderation - Modrinth',
  },
  computed: {
    moderationTypes() {
      const obj = {}

      for (const project of this.projects) {
        obj[project.project_type] = true
      }

      if (this.reports.length > 0) {
        obj.report = true
      }

      return Object.keys(obj)
    },
  },
  methods: {
    setProjectStatus(project, status) {
      project.moderation_message = ''
      project.moderation_message_body = ''
      project.newStatus = status

      this.currentProject = project
      this.$refs.modal.show()
    },
    async saveProject() {
      this.$nuxt.$loading.start()

      try {
        await this.$axios.patch(
          `project/${this.currentProject.id}`,
          {
            moderation_message: this.currentProject.moderation_message
              ? this.currentProject.moderation_message
              : null,
            moderation_message_body: this.currentProject.moderation_message_body
              ? this.currentProject.moderation_message_body
              : null,
            status: this.currentProject.newStatus,
          },
          this.$defaultHeaders()
        )

        this.projects.splice(
          this.projects.findIndex((x) => this.currentProject.id === x.id),
          1
        )
        this.currentProject = null
        this.$refs.modal.hide()
      } catch (err) {
        this.$notify({
          group: 'main',
          title: 'An error occurred',
          text: err.response.data.description,
          type: 'error',
        })
      }

      this.$nuxt.$loading.finish()
    },
    async deleteReport(index) {
      this.$nuxt.$loading.start()

      try {
        await this.$axios.delete(
          `report/${this.reports[index].id}`,
          this.$defaultHeaders()
        )

        this.reports.splice(index, 1)
      } catch (err) {
        this.$notify({
          group: 'main',
          title: 'An error occurred',
          text: err.response.data.description,
          type: 'error',
        })
      }

      this.$nuxt.$loading.finish()
    },
  },
}
</script>

<style lang="scss" scoped>
.moderation-modal {
  width: auto;
  padding: var(--spacing-card-md) var(--spacing-card-lg);

  .status {
    display: flex;
    align-items: center;
    margin-bottom: 0.5rem;

    span {
      margin-right: 0.5rem;
    }
  }

  .textarea-wrapper {
    margin-top: 0.5rem;
    height: 15rem;

    .preview {
      overflow-y: auto;
    }
  }

  .separator {
    margin: var(--spacing-card-sm) 0;
  }

  .buttons {
    display: flex;
    margin-top: 0.5rem;

    :first-child {
      margin-left: auto;
    }
  }
}

h1 {
  color: var(--color-text-dark);
}

.report {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  gap: 1rem;
  padding: 1rem;

  > div {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
  }

  .info {
    display: flex;
    flex-wrap: wrap;

    .title {
      display: flex;
      align-items: baseline;
      gap: 0.25rem;
      flex-wrap: wrap;

      h3 {
        margin: 0;
        text-transform: capitalize;

        a {
          text-transform: none;
        }
      }

      a {
        text-decoration: underline;
      }
    }
  }

  .actions {
    min-width: fit-content;

    .iconified-button {
      margin-left: auto;
      width: fit-content;
    }

    .stat {
      margin-top: auto;
      display: flex;
      align-items: center;
      grid-gap: 0.5rem;

      svg {
        width: 1em;
      }
    }
  }
}

@media screen and (min-width: 1024px) {
  .page-contents {
    max-width: 800px;
  }
}
</style>

// src/routes/moderation.svelte
<script context="module" lang="ts">
	import { create } from '$utils/create'
	import { send } from 'omorphia/utils'

	export const load: import('./__types/moderation').Load = async ({ fetch }) => {
		try {
			let [projects, reports] = await Promise.all([
				send<'getModerationProjects'>('GET', 'moderation/projects', null, { fetch }),
				send<'getReports'>('GET', 'report', null, { fetch }),
			])

			projects = projects.map((it) => ({
				...it,
				moderation_type: it.project_type,
			}))

			reports = await Promise.all(
				reports.map(async (report) => {
					report.item_id = report.item_id?.replace
						? report.item_id.replace(/"/g, '')
						: report.item_id
					let url = ''

					if (report.item_type === 'user') {
						const user = await send<'getUser'>('GET', `user/${report.item_id}`, null, { fetch })
						url = `/user/${user.username}`
						report.item_id = user.username
					} else if (report.item_type === 'project') {
						const project = await send<'getProject'>('GET', `project/${report.item_id}`, null, {
							fetch,
						})
						report.item_id = project.slug || report.item_id
						url = `/${project.project_type}/${report.item_id}`
					} else if (report.item_type === 'version') {
						const version = await send<'getVersion'>('GET', `version/${report.item_id}`, null, {
							fetch,
						})
						const project = await send<'getProject'>('GET', `project/${version.project_id}`, null, {
							fetch,
						})
						report.item_id = version.version_number || report.item_id
						url = `/${project.project_type}/${project.slug || project.id}/version/${report.item_id}`
					}

					report.reporter = (
						await send<'getUser'>('GET', `user/${report.reporter}`, null, { fetch })
					).username

					return {
						...report,
						moderation_type: 'report',
						url,
					}
				})
			)

			interface ReportItem {
				published?: boolean
				created?: boolean
			}

			const items = [...projects, ...reports].sort(
				(a: any, b: any) =>
					new Date(a.published || a.created).valueOf() -
					new Date(b.published || b.created).valueOf()
			)
			return {
				props: {
					items,
				},
			}
		} catch {
			return {
				status: 404,
				error: new Error(`The moderation queue could not be received.`),
			}
		}
	}
</script>

<script lang="ts">
	import { NavRow } from 'omorphia'
	import { projectTypes } from '$generated/tags.json'
	import { t } from 'svelte-intl-precompile'
	import Meta from '$components/utils/Meta.svelte'
	import ProjectCard from '$components/elements/ProjectCard.svelte'
	import { page } from '$app/stores'
	import { Button, Badge, Field, Select, TextInput, Modal } from 'omorphia'
	import { ago, markdown } from 'omorphia/utils'
	import IconCalendar from 'virtual:icons/lucide/calendar'
	import IconEye from 'virtual:icons/heroicons-outline/eye'
	import IconTrash from 'virtual:icons/heroicons-outline/trash'
	import IconCheck from 'virtual:icons/heroicons-outline/check'
	import NoData from '$assets/images/illustrations/undraw_no_data.svg'

	export let items

	let newStatus: any = {}

	$: filteredItems = items.filter((item) =>
		$page.url.searchParams.get('type')
			? item.moderation_type === $page.url.searchParams.get('type')
			: true
	)

	async function changeStatus(id: string) {
		await send('PATCH', `project/${id}`, {
			status: newStatus.status,
			...(newStatus.body
				? {
						moderation_message: 'Moderator message',
						moderation_message_body: newStatus.body,
				  }
				: {}),
		})
		removeItem(id)
	}

	function removeItem(id: string) {
		items = items.filter((item) => item.id !== id)
	}
</script>

<Meta title={$t('pages.moderation')} noindex />

<div class="single-layout">
	<h1>{$t('pages.moderation')}</h1>
	<div class="card">
		<NavRow
			links={[
				{
					label: $t('pages.all'),
					href: '',
				},
				{
					label: $t('report.plural'),
					href: 'report',
				},
				...projectTypes.map((type) => ({
					label: $t(`project.types.${type}.plural`),
					href: type,
				})),
			]}
			query="type" />
	</div>

	{#if filteredItems.length > 0}
		{#each filteredItems as item}
			{#if item.moderation_type === 'report'}
				<div class="card report">
					<div class="report__info">
						<div class="report__info__title">
							<h3>{item.item_type} <a href={item.url}>{item.item_id}</a></h3>
							reported by<a href="/user/{item.reporter}">{item.reporter}</a>
						</div>
						{#if item.body}
							{@html markdown(item.body)}
						{/if}
						<Badge label="Marked as {item.report_type}" color="yellow" />
					</div>
					<div class="actions">
						<Button
							on:click={async () => {
								await send('DELETE', `report/${item.id}`)
								removeItem(item.id)
							}}>
							<IconTrash /> Delete report
						</Button>
						<span class="stat">
							<IconCalendar />
							{@html $t('stats.created', { values: { ago: ago(item.created) } })}
						</span>
					</div>
				</div>
			{:else}
				<ProjectCard project={item}>
					<div slot="actions" class="actions">
						<Modal
							title={$t('modal.moderation.project_status.title')}
							let:trigger
							bind:data={newStatus}
							defaultData={{
								status: 'approve',
							}}>
							<Button slot="trigger" on:click={trigger}>
								<IconEye /> Change status
							</Button>

							<Field label={$t('modal.moderation.project_status.fields.status.label')}>
								<Select
									bind:value={newStatus.status}
									options={[
										{
											label: $t('modal.moderation.project_status.fields.status.options.approve'),
											value: 'approved',
										},
										{
											label: $t('modal.moderation.project_status.fields.status.options.unlist'),
											value: 'unlisted',
										},
										{
											label: $t('modal.moderation.project_status.fields.status.options.reject'),
											value: 'rejected',
										},
									]} />
							</Field>
							<Field
								label={$t('modal.moderation.project_status.fields.moderation_message.label')}
								helper={$t('modal.moderation.project_status.fields.moderation_message.helper')}>
								<TextInput
									multiline
									placeholder={$t(
										'modal.moderation.project_status.fields.moderation_message.placeholder'
									)}
									bind:value={newStatus.body} />
							</Field>

							<Button
								color="primary"
								slot="button"
								let:close
								on:click={() => {
									changeStatus(item.id)
									close()
								}}><IconCheck /> {$t('modal.moderation.project_status.action')}</Button>
						</Modal>

						<span class="stat">
							<IconCalendar />
							{@html $t('stats.created', { values: { ago: ago(item.published) } })}
						</span>
					</div>
				</ProjectCard>
			{/if}
		{/each}
	{:else}
		<div class="illustration">
			<NoData class="illustration__image" />
			<p class="illustration__description">You are up to date!</p>
		</div>
	{/if}
</div>

<style lang="postcss">
	.report {
		display: flex;
		flex-direction: row;
		justify-content: space-between;
		flex-wrap: wrap;
		gap: 1rem;

		> div {
			display: flex;
			flex-direction: column;
			gap: 0.75rem;
		}

		&__info {
			display: flex;
			flex-wrap: wrap;

			&__title {
				display: flex;
				align-items: center;
				gap: 0.5rem;
				flex-wrap: wrap;

				h3 {
					text-transform: capitalize;

					a {
						text-transform: none;
					}
				}

				a {
					text-decoration: underline;
				}
			}
		}
	}
</style>
