// pages/dashboard/notifications.vue
<template>
  <div>
    <div class="section-header columns">
      <h3 class="column-grow-1">My notifications</h3>
    </div>
    <div v-if="notifications.length !== 0">
      <div
        v-for="notification in notifications"
        :key="notification.id"
        class="notification columns"
      >
        <div class="text">
          <nuxt-link :to="'/' + notification.link" class="top-wrapper">
            <h3 class="title">
              {{ notification.title }}
            </h3>
            <p
              v-tooltip="
                $dayjs(notification.created).format(
                  '[Created at] YYYY-MM-DD [at] HH:mm A'
                )
              "
              class="date"
            >
              Notified {{ $dayjs(notification.created).fromNow() }}
            </p>
          </nuxt-link>
          <p class="description">
            {{ notification.text }}
          </p>
        </div>
        <div v-if="notification.actions.length > 0" class="actions">
          <button
            v-for="(action, index) in notification.actions"
            :key="index"
            @click="performAction(notification, index)"
          >
            {{ action.title }}
          </button>
        </div>
        <div v-else class="actions">
          <button @click="performAction(notification, null)">Dismiss</button>
        </div>
      </div>
    </div>
    <div v-else class="error">
      <UpToDate class="icon"></UpToDate>
      <br />
      <span class="text">You are up-to-date!</span>
    </div>
  </div>
</template>

<script>
import axios from 'axios'
import UpToDate from '~/assets/images/illustrations/up_to_date.svg?inline'

export default {
  components: {
    UpToDate,
  },
  async asyncData(data) {
    const notifications = (
      await axios.get(
        `https://api.modrinth.com/api/v1/user/${data.$auth.user.id}/notifications`,
        data.$auth.headers
      )
    ).data

    return {
      notifications,
    }
  },
  methods: {
    async performAction(notification, index) {
      this.$nuxt.$loading.start()

      try {
        if (index) {
          const config = {
            method: notification.actions[index].action_route[0].toLowerCase(),
            url: `https://api.modrinth.com/api/v1/${notification.actions[index].action_route[1]}`,
            headers: {
              Authorization: this.$auth.token,
            },
          }

          await axios(config)
        }

        await axios.delete(
          `https://api.modrinth.com/api/v1/notification/${notification.id}`,
          this.$auth.headers
        )

        this.notifications.splice(index, 1)
      } catch (err) {
        this.$notify({
          group: 'main',
          title: 'An Error Occurred',
          text: err.response.data.description,
          type: 'error',
        })
      }

      this.$nuxt.$loading.finish()
    },
  },
  head: {
    title: 'Notifiations - Modrinth',
  },
}
</script>

<style lang="scss" scoped>
.notification {
  @extend %card;
  padding: var(--spacing-card-sm) var(--spacing-card-lg);
  margin-bottom: var(--spacing-card-sm);
  align-items: center;
  justify-content: space-between;

  .text {
    .top-wrapper {
      display: flex;
      flex-direction: row;
      align-items: baseline;

      .title {
        font-size: var(--font-size-lg);
        margin: 0 0.5rem 0 0;
      }
    }
  }

  p {
    margin: 0;
  }
}

.error {
  display: flex;
  flex-direction: column;
  width: 100%;
  justify-content: center;
  align-items: center;

  .icon {
    width: 8rem;
    height: 8rem;
    margin: 1.5rem 0;
  }

  .text {
    margin-bottom: 2rem;
    font-size: 1.25rem;
  }

  .link {
    text-decoration: underline;
  }
}
</style>

// src/routes/notifications.svelte
<script lang="ts">
  import { t } from 'svelte-intl-precompile'
  import Meta from '$components/utils/Meta.svelte'
  import { notifications, updateSelf, loaded } from '$stores/self'
  import { markdownInline } from '$lib/parse'
  import { ago } from '$lib/ago'
  import Button from '$components/elements/Button.svelte'
  import IconTrash from 'virtual:icons/heroicons-outline/trash'
  import { send } from '$lib/api'
  import { onMount } from 'svelte'
  import UpToDate from '$assets/images/illustrations/undraw_notify.svg'

  onMount(async () => {
    await updateSelf()
  })

  async function deleteNotification(id) {
    await send('DELETE', `notification/${id}`)
    $notifications = $notifications.filter(it => it.id !== id)
  }
</script>

<Meta title={$t('pages.notifications')}/>

<div class="single-layout">
  <div class="title-bar">
    <h1>{$t('pages.notifications')}</h1>
    {#if !$loaded || $notifications.length > 0}
      <Button label="Clear all" color="brand" icon={IconTrash} on:click={async () => {
        await send('DELETE', `notifications?ids=${JSON.stringify($notifications.map(it => it.id))}`)
        $notifications = []
      }}/>
    {/if}
  </div>
  {#if !$loaded}
    Loading notifications...
  {:else if $notifications.length > 0}
    {#each $notifications as notification}
      <div class="card notification">
        <div class="notification__info">
          <div class="notification__info__title">
            <h3><a href={notification.link}>
              {@html markdownInline(notification.title)}
            </a></h3>
            <span class="notification__info__title__time">
          {@html $t('stats.notified', {values: {ago: ago(notification.created)}})}
        </span>
          </div>
          <p>{notification.text}</p>
        </div>
        <div class="notification__actions">
          {#if notification.type === 'project_update'}
            <Button label="Clear" icon={IconTrash} on:click={async () => {
          await deleteNotification(notification.id)
    }}/>
          {/if}
          {#each notification.actions as action}
            <Button label={action.title} on:click={async () => {
            try {
              await send(action.action_route[0], action.action_route[1])
            } catch {
              // Workaround for https://github.com/modrinth/labrinth/issues/279
              console.warn('Could not perform notification action.')
            }
            await deleteNotification(notification.id)
          }}/>
          {/each}
        </div>
      </div>
    {/each}
  {:else}
    <div class="illustration">
      <UpToDate class="illustration__image" />
      <p class="illustration__description">You are up to date!</p>
    </div>
  {/if}
</div>

<style lang="postcss">
  .title-bar {
    display: flex;
    justify-content: space-between;
    align-items: flex-end;

    @media (width <= 400px) {
      flex-direction: column;
      align-items: flex-start;
      grid-gap: 0.75rem;
    }
  }

  .notification {
    display: flex;
    flex-direction: row;
    justify-content: space-between;

    @media (width <= 800px) {
      flex-direction: column;
    }

    &__info {
      display: flex;
      flex-direction: column;
      grid-gap: 0.5rem;

      &__title {
        display: flex;
        flex-direction: row;
        align-items: center;
        grid-gap: 0.5rem;

        @media (width <= 800px) {
          flex-direction: column;
          align-items: flex-start;
        }

        :global(strong) {
          text-decoration: underline;
        }

        &__time {
          color: var(--color-text-light)
        }
      }
    }

    &__actions {
      display: flex;
      flex-direction: row;
      align-items: flex-end;
      grid-gap: 0.5rem;
    }
  }
</style>
