// pages/notifications.vue
<template>
  <div class="page-container">
    <div class="page-contents">
      <div class="content">
        <h1>{{ $t('notifications.title') }}</h1>

        <div class="divider card">
          <NavRow
            query="type"
            :links="[
              {
                label: $t('notifications.category.all'),
                href: '',
              },
              ...notificationTypes.map((x) => {
                return {
                  label: $t(`notifications.category.${x.replace(/_/g, '-')}`),
                  href: x,
                }
              }),
            ]"
          />
          <button
            class="iconified-button brand-button"
            @click="clearNotifications"
          >
            <ClearIcon /> {{ $t('notifications.actions.clear-all') }}
          </button>
        </div>
        <div class="notifications">
          <div
            v-for="notification in $route.query.type !== undefined
              ? $user.notifications.filter((x) => x.type === $route.query.type)
              : $user.notifications"
            :key="notification.id"
            class="card notification"
          >
            <div class="text">
              <nuxt-link :to="notification.link" class="top">
                <h3 v-html="$xss($md.render(notification.title))" />
                <span
                  v-tooltip="
                    $fmt.date(notification.created, {
                      dateStyle: 'long',
                      timeStyle: 'medium',
                    })
                  "
                >
                  {{
                    $t('notifications.notification.notified-ago', {
                      ago: $fmt.timeDifference(notification.created),
                    })
                  }}
                </span>
              </nuxt-link>
              <p>{{ notification.text }}</p>
            </div>
            <div class="buttons">
              <button
                v-for="(action, actionIndex) in notification.actions"
                :key="actionIndex"
                class="iconified-button"
                @click="
                  performAction(notification, notificationIndex, actionIndex)
                "
              >
                {{ action.title }}
              </button>
              <button
                v-if="notification.actions.length === 0"
                class="iconified-button"
                @click="performAction(notification, notificationIndex, null)"
              >
                {{ $t('notifications.notification.actions.dismiss') }}
              </button>
            </div>
          </div>
          <div v-if="$user.notifications.length === 0" class="error">
            <UpToDate class="icon"></UpToDate>
            <br />
            <span class="text">{{ $t('notifications.no-notifications') }}</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import ClearIcon from '~/assets/images/utils/clear.svg?inline'
import UpToDate from '~/assets/images/illustrations/up_to_date.svg?inline'
import NavRow from '~/components/ui/NavRow'

const NOTIFICATION_TYPES = {
  team_invite: 'Team invites',
  project_update: 'Project updates',
}

export default {
  name: 'Notifications',
  components: {
    NavRow,
    ClearIcon,
    UpToDate,
  },
  async fetch() {
    this.NOTIFICATION_TYPES = NOTIFICATION_TYPES

    await this.$store.dispatch('user/fetchNotifications')
  },
  head() {
    return {
      title: this.$t('meta.title-format', {
        title: this.$t('notifications.title'),
      }),
    }
  },
  computed: {
    notificationTypes() {
      const obj = {}

      for (const notification of this.$user.notifications.filter(
        (it) => it.type !== null
      )) {
        obj[notification.type] = true
      }

      return Object.keys(obj)
    },
  },
  methods: {
    async clearNotifications() {
      try {
        const ids = this.$user.notifications.map((x) => x.id)

        await this.$axios.delete(
          `notifications?ids=${JSON.stringify(ids)}`,
          this.$defaultHeaders()
        )

        ids.forEach((x) => this.$store.dispatch('user/deleteNotification', x))
      } catch (err) {
        this.$notify({
          group: 'main',
          title: this.$t('error.generic'),
          text: err.response.data.description,
          type: 'error',
        })
      }
    },
    async performAction(notification, notificationIndex, actionIndex) {
      this.$nuxt.$loading.start()
      try {
        await this.$axios.delete(
          `notification/${notification.id}`,
          this.$defaultHeaders()
        )

        await this.$store.dispatch('user/deleteNotification', notification.id)

        if (actionIndex !== null) {
          const config = {
            method:
              notification.actions[actionIndex].action_route[0].toLowerCase(),
            url: `${notification.actions[actionIndex].action_route[1]}`,
            headers: {
              Authorization: this.$auth.token,
            },
          }
          await this.$axios(config)
        }
      } catch (err) {
        this.$notify({
          group: 'main',
          title: this.$t('error.generic'),
          text: err.response.data.description,
          type: 'error',
        })
      }
      this.$nuxt.$loading.finish()
    },
  },
}
</script>

<style lang="scss" scoped>
h1 {
  color: var(--color-text-dark);
}

.divider {
  align-items: center;
  display: flex;
  justify-content: space-between;
  flex-wrap: wrap;
  row-gap: 0.5rem;
}

.notifications {
  .notification {
    display: flex;
    flex-wrap: wrap;
    padding: var(--spacing-card-md) var(--spacing-card-lg);

    .text {
      display: flex;
      flex-direction: column;
      justify-content: space-between;

      .top {
        display: flex;
        align-items: baseline;
        flex-direction: column;
        margin-bottom: 0.5rem;

        h3 ::v-deep {
          font-size: var(--font-size-lg);
          margin: 0 0.5rem 0 0;

          p {
            margin: 0;

            strong {
              text-decoration: underline;
            }
          }
        }

        span {
          color: var(--color-icon);
        }
      }

      p {
        padding: 0;
        margin: 0;
      }
    }

    .buttons {
      display: flex;
      flex-direction: column;
      justify-content: center;
      margin-left: auto;
      text-align: right;

      button {
        margin-left: auto;
        margin-bottom: 0.25rem;
      }
    }
  }
}

@media screen and (min-width: 1024px) {
  .page-contents {
    max-width: calc(800px) !important;
  }

  .notifications {
    .notification {
      flex-wrap: nowrap;

      .text {
        flex-direction: column;

        .top {
          flex-direction: row;
        }
      }
    }
  }
}
</style>

// src/routes/notifications.svelte
<script lang="ts">
  import { t } from 'svelte-intl-precompile'
  import Meta from '$components/utils/Meta.svelte'
  import { notifications, updateSelf, loaded } from '$stores/self'
  import { markdownInline } from '$lib/parse'
  import { ago } from '$lib/ago'
  import Button from '$components/elements/Button.svelte'
  import IconTrash from 'virtual:icons/heroicons-outline/trash'
  import { send } from '$lib/api'
  import { onMount } from 'svelte'
  import UpToDate from '$assets/images/illustrations/undraw_notify.svg'

  onMount(async () => {
    await updateSelf()
  })

  async function deleteNotification(id) {
    await send('DELETE', `notification/${id}`)
    $notifications = $notifications.filter(it => it.id !== id)
  }
</script>

<Meta title={$t('pages.notifications')}/>

<div class="single-layout">
  <div class="title-bar">
    <h1>{$t('pages.notifications')}</h1>
    {#if !$loaded || $notifications.length > 0}
      <Button label="Clear all" color="brand" icon={IconTrash} on:click={async () => {
        await send('DELETE', `notifications?ids=${JSON.stringify($notifications.map(it => it.id))}`)
        $notifications = []
      }}/>
    {/if}
  </div>
  {#if !$loaded}
    Loading notifications...
  {:else if $notifications.length > 0}
    {#each $notifications as notification}
      <div class="card notification">
        <div class="notification__info">
          <div class="notification__info__title">
            <h3><a href={notification.link}>
              {@html markdownInline(notification.title)}
            </a></h3>
            <span class="notification__info__title__time">
          {@html $t('stats.notified', {values: {ago: ago(notification.created)}})}
        </span>
          </div>
          <p>{notification.text}</p>
        </div>
        <div class="notification__actions">
          {#if notification.type === 'project_update'}
            <Button label="Clear" icon={IconTrash} on:click={async () => {
          await deleteNotification(notification.id)
    }}/>
          {/if}
          {#each notification.actions as action}
            <Button label={action.title} on:click={async () => {
            try {
              await send(action.action_route[0], action.action_route[1])
            } catch {
              // Workaround for https://github.com/modrinth/labrinth/issues/279
              console.warn('Could not perform notification action.')
            }
            await deleteNotification(notification.id)
          }}/>
          {/each}
        </div>
      </div>
    {/each}
  {:else}
    <div class="illustration">
      <UpToDate class="illustration__image" />
      <p class="illustration__description">You are up to date!</p>
    </div>
  {/if}
</div>

<style lang="postcss">
  .title-bar {
    display: flex;
    justify-content: space-between;
    align-items: flex-end;

    @media (width <= 400px) {
      flex-direction: column;
      align-items: flex-start;
      grid-gap: 0.75rem;
    }
  }

  .notification {
    display: flex;
    flex-direction: row;
    justify-content: space-between;

    @media (width <= 800px) {
      flex-direction: column;
    }

    &__info {
      display: flex;
      flex-direction: column;
      grid-gap: 0.5rem;

      &__title {
        display: flex;
        flex-direction: row;
        align-items: center;
        grid-gap: 0.5rem;

        @media (width <= 800px) {
          flex-direction: column;
          align-items: flex-start;
        }

        :global(strong) {
          text-decoration: underline;
        }

        &__time {
          color: var(--color-text-light)
        }
      }
    }

    &__actions {
      display: flex;
      flex-direction: row;
      align-items: flex-end;
      grid-gap: 0.5rem;
    }
  }
</style>
