// components/app/Header.vue
<template>
  <header class="header wide-page">
    <!-- This wrapper is neccessary because flexbox doesn't account for padding in its calculations. Hence we have to use margin with flexbox, unfortunately -->
    <div class="header__wrapper">
      <div class="header__collapsible">
        <nav class="header__mobile-nav dropdown dropdown_align_left">
          <button class="dropdown__control">
            <HamburgerIcon />
          </button>
          <ul class="dropdown__content card" @click="removeFocus">
            <li>
              <NuxtLink to="/mods" class="dropdown-item">
                <span class="dropdown-item__text">Mods</span>
              </NuxtLink>
            </li>
            <li>
              <NuxtLink to="/modpacks" class="dropdown-item">
                <span class="dropdown-item__text">Modpacks</span>
              </NuxtLink>
            </li>
          </ul>
        </nav>
        <NuxtLink class="header__logo-wrapper" to="/">
          <ModrinthIcon class="header__icon" />
          <ModrinthLogo class="header__logo" />
        </NuxtLink>
        <nav class="header__desktop-nav styled-tabs">
          <NuxtLink to="/mods" class="tab">
            <span>Mods</span>
          </NuxtLink>
          <NuxtLink to="/modpacks" class="tab">
            <span>Modpacks</span>
          </NuxtLink>
        </nav>
      </div>
      <div class="header__user-controls">
        <button class="header__user-control user-control" @click="changeTheme">
          <MoonIcon v-if="$colorMode.value === 'light'" />
          <SunIcon v-else />
        </button>
        <template v-if="$auth.user">
          <NuxtLink
            to="/notifications"
            class="header__user-control user-control"
          >
            <NotificationIcon />
            <div
              v-if="$user.notifications.length > 0"
              class="user-control__bubble"
            >
              {{ $user.notifications.length }}
            </div>
          </NuxtLink>
          <div class="header__user-dropdown dropdown">
            <button class="dropdown__control">
              <img
                :src="$auth.user.avatar_url"
                class="dropdown__control-image"
              />
              <span class="dropdown__control-caret"></span>
            </button>
            <ul class="dropdown__content card" @click="removeFocus">
              <li>
                <NuxtLink
                  class="dropdown-item"
                  :to="`/user/${$auth.user.username}`"
                >
                  <div class="dropdown-item__text dropdown-profile">
                    <div class="dropdown-profile__username">
                      @{{ $auth.user.username }}
                    </div>
                    <div class="dropdown-profile__prompt">Go to my profile</div>
                  </div>
                </NuxtLink>
              </li>
              <hr class="dropdown__divider" />
              <li>
                <NuxtLink class="dropdown-item" to="/create/project">
                  <CreateIcon class="dropdown-item__icon" />
                  <span class="dropdown-item__text">Create a project</span>
                </NuxtLink>
              </li>
              <hr class="dropdown__divider" />
              <li>
                <NuxtLink class="dropdown-item" to="/notifications">
                  <NotificationIcon class="dropdown-item__icon" />
                  <span class="dropdown-item__text">Notifications</span>
                </NuxtLink>
              </li>
              <li>
                <NuxtLink class="dropdown-item" to="/settings">
                  <SettingsIcon class="dropdown-item__icon" />
                  <span class="dropdown-item__text">Settings</span>
                </NuxtLink>
              </li>
              <li>
                <NuxtLink
                  v-if="
                    $auth.user.role === 'moderator' ||
                    $auth.user.role === 'admin'
                  "
                  class="dropdown-item"
                  to="/moderation"
                >
                  <ModerationIcon class="dropdown-item__icon" />
                  <span class="dropdown-item__text">Moderation</span>
                </NuxtLink>
              </li>
              <li>
                <button class="dropdown-item" @click="changeTheme">
                  <MoonIcon
                    v-if="$colorMode.value === 'light'"
                    class="dropdown-item__icon"
                  />
                  <SunIcon v-else class="dropdown-item__icon" />
                  <span class="dropdown-item__text">Change theme</span>
                </button>
              </li>
              <hr class="dropdown__divider" />
              <li>
                <button class="dropdown-item" @click="logout">
                  <LogOutIcon class="dropdown-item__icon" />
                  <span class="dropdown-item__text">Log out</span>
                </button>
              </li>
            </ul>
          </div>
        </template>
        <a
          v-else
          :href="authUrl"
          class="header__signin iconified-button brand-button-colors"
        >
          <GitHubIcon />
          <div>
            <span>Sign in</span>
            <span class="header__signin-clippable">with GitHub</span>
          </div>
        </a>
      </div>
    </div>
  </header>
</template>

<script>
import ModrinthLogo from '~/assets/images/text-logo.svg?inline'
import ModrinthIcon from '~/assets/images/logo.svg?inline'

import HamburgerIcon from '~/assets/images/utils/hamburger.svg?inline'

import CreateIcon from '~/assets/images/utils/plus.svg?inline'
import NotificationIcon from '~/assets/images/sidebar/notifications.svg?inline'
import SettingsIcon from '~/assets/images/sidebar/settings.svg?inline'
import ModerationIcon from '~/assets/images/sidebar/admin.svg?inline'

import MoonIcon from '~/assets/images/utils/moon.svg?inline'
import SunIcon from '~/assets/images/utils/sun.svg?inline'

import LogOutIcon from '~/assets/images/utils/log-out.svg?inline'
import GitHubIcon from '~/assets/images/utils/github.svg?inline'

export default {
  components: {
    ModrinthLogo,
    ModrinthIcon,
    MoonIcon,
    SunIcon,
    LogOutIcon,
    GitHubIcon,
    CreateIcon,
    NotificationIcon,
    HamburgerIcon,
    SettingsIcon,
    ModerationIcon,
  },
  computed: {
    authUrl() {
      return `${this.$axios.defaults.baseURL}auth/init?url=${process.env.domain}${this.$route.path}`
    },
  },
  methods: {
    async logout() {
      this.$cookies.set('auth-token-reset', true)
      // If users logs out on dashboard, force redirect on the home page to clear cookies
      if (this.$route.path.startsWith('/settings')) {
        window.location.href = '/'
      } else {
        await this.$router.go(null)

        this.$notify({
          group: 'main',
          title: 'Logged Out',
          text: 'You have logged out successfully!',
          type: 'success',
        })
      }
    },
    changeTheme() {
      this.$colorMode.preference =
        this.$colorMode.value === 'dark' ? 'light' : 'dark'
    },
    removeFocus() {
      document.activeElement.blur()
    },
  },
}
</script>

<style scoped>
.header__wrapper {
  align-items: center;
  display: flex;
  justify-content: space-between;
  margin: 1rem 1.5rem;
}

.header__collapsible,
.header__logo-wrapper {
  align-items: center;
  display: flex;
}

.header__icon,
.header__logo {
  height: 2rem;
  width: auto;
}

.header__icon {
  margin-left: 1rem;
}

.header__logo {
  display: none;
}

.header__desktop-nav {
  display: none;
  margin-left: 2rem;
}

.header__user-controls {
  align-items: center;
  display: flex;
}

.header__user-control {
  margin-left: 0.25rem;
}

.header__user-dropdown,
.header__signin {
  margin: 0 0 0 0.75rem;
}

.header__signin-clippable {
  display: none;
}

.user-control {
  align-items: center;
  background: none;
  border-radius: 100%;
  display: flex;
  height: 2.5rem;
  justify-content: center;
  padding: 0;
  position: relative;
  width: 2.5rem;
}

.user-control__bubble {
  position: absolute;
  top: 0;
  right: -0.3rem;
  border-radius: 1rem;
  padding: 0.1rem 0.25rem;
  font-size: 0.75rem;
  background-color: var(--color-brand);
  color: var(--color-brand-inverted);
}

.user-control:hover {
  background-color: var(--color-button-bg-hover);
}

.dropdown {
  position: relative;
}

.dropdown:hover .dropdown__control-image,
.dropdown:focus .dropdown__control-image,
.dropdown:focus-within .dropdown__control-image {
  outline-color: var(--color-brand);
}

.dropdown:hover .dropdown__content,
.dropdown:focus .dropdown__content,
.dropdown:focus-within .dropdown__content {
  opacity: 1;
  transform: scaleY(1);
  visibility: visible;
}

.dropdown__control {
  align-items: center;
  background: none;
  display: flex;
  justify-content: center;
  padding: 0;
}

.dropdown__control-image {
  border-radius: 100%;
  height: 2rem;
  outline: 2px solid transparent;
  width: 2rem;
}

.dropdown__control-caret::after {
  content: '\23F7';
  color: inherit;
  margin-left: 0.25rem;
}

.dropdown__content {
  border: 1px solid var(--color-divider-dark);
  list-style: none;
  margin: 0.5rem 0 0 0;
  max-width: 25rem;
  min-width: 12rem;
  opacity: 0;
  padding: 1rem;
  position: absolute;
  right: -1rem;
  transform: scaleY(0.9);
  transform-origin: top;
  transition: all 0.1s ease-in-out 0.05s;
  visibility: hidden;
  width: max-content;
  z-index: 1;
}

.dropdown_align_left .dropdown__content {
  right: auto;
  left: -1rem;
}

.dropdown__divider {
  background-color: var(--color-divider-dark);
  border: none;
  color: var(--color-divider-dark);
  height: 1px;
  margin: 0.5rem 0;
}

.dropdown-item {
  align-items: center;
  background: none;
  border-radius: 0.5rem;
  box-sizing: border-box;
  color: inherit;
  display: flex;
  padding: 0.5rem;
  width: 100%;
}

.dropdown-item:hover,
.dropdown-item:focus {
  background-color: var(--color-bg);
}

.dropdown-item__icon {
  margin-right: 0.5rem;
  height: var(--size-icon);
  width: var(--size-icon);
}

.dropdown-profile__prompt {
  margin-top: 0.25rem;
  color: var(--color-text-secondary);
}

@media screen and (min-width: 1024px) {
  .header__wrapper {
    margin: 1rem;
  }

  .header__mobile-nav {
    display: none;
  }

  .header__icon {
    display: none;
  }

  .header__logo {
    display: block;
  }

  .header__desktop-nav {
    display: inherit;
  }

  .header__signin-clippable {
    display: inline;
  }
}
</style>

// src/components/layout/Header.svelte
<script lang="ts">
  import { t } from 'svelte-intl-precompile'
  import Nav from '$components/elements/Nav.svelte'
  import Button from '$components/elements/Button.svelte'
  import IconBell from 'virtual:icons/fa-regular/bell'
  import IconGitHub from 'virtual:icons/simple-icons/github'
  import { browser } from '$app/env'
  import { token, user } from '$stores/server'
  import { projectTypes } from '$generated/tags.json'
  import { setContext } from 'svelte'
  import LogoLoader from '$components/elements/LogoLoader.svelte'
  import { notifications } from '$stores/self'
  import IconChevronDown from 'virtual:icons/lucide/chevron-down'
  import IconSettings from 'virtual:icons/lucide/settings'
  import IconLogout from 'virtual:icons/lucide/log-out'
  import IconHeart from 'virtual:icons/lucide/heart'
  import IconModeration from 'virtual:icons/fa-regular/life-ring'
  import IconPlus from 'virtual:icons/heroicons-outline/plus'
  import { create } from '$lib/create'

  let navItems = projectTypes.map((type) => ({
    label: $t(`project.types.${type}.plural`),
    href: `/${$t(`project.types.${type}.plural`, {locale: 'en'}).toLowerCase()}`,
  }))
  setContext('navItems', navItems)

  let hideDropdown: boolean

  let dropdown
  $: dropdown = [
    {
      label: '@' + $user?.username,
      sublabel: 'Go to my profile',
      href: `/user/${$user?.username}`,
    },
    {
      divider: true,
    },
    ...(['admin', 'moderator'].includes($user?.role) ? [{
      label: 'Moderation',
      href: '/moderation',
      icon: IconModeration,
    }] : []),
    {
      label: 'Following',
      href: '/following',
      icon: IconHeart,
    },
    {
      label: 'Create',
      action: create,
      icon: IconPlus,
    },
    {
      label: 'Settings',
      href: '/settings',
      icon: IconSettings,
    },
    {
      divider: true,
    },
    {
      label: 'Log out',
      action: () => {
        $user = null
        $token = ''
        document.cookie =
          'modrinth-token' + '=test; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;'
        // window.location.replace($page.url.toString()); // Reloads page after logout
      },
      icon: IconLogout,
    },
  ]
</script>

<header class="header">
  <a href="/" aria-label="Modrinth Home">
    <LogoLoader height={'24px'}/>
  </a>
  <Nav level={0} links={navItems}/>

  <div class="header__actions">
    {#if $user}
      <Button href="/notifications" color="transparent" title="Notifications" icon={IconBell} badge={$notifications.length > 0}/>
      <div
        class="avatar"
        class:hide-dropdown={hideDropdown}
        tabindex="0"
      >
        <div class="avatar__toggle" on:mouseover={() => hideDropdown = false} on:focus={() => hideDropdown = false}>
          <img class="avatar__toggle__image" src={$user.avatar_url} alt={$user.username}/>
          <IconChevronDown/>
        </div>
        <div class="avatar__dropdown">
          {#each dropdown as item}
            {#if item.divider}
              <hr class="divider"/>
            {:else if item.href}
              <a href={item.href} class="avatar__dropdown__item" on:click={() => hideDropdown = true}>
                {#if item.icon}
                  <svelte:component this={item.icon} height={16} width={16}/>
                {/if}
                <span class="avatar__dropdown__item__label">
						{item.label}
                  {#if item.sublabel}
							<br/><span class="avatar__dropdown__item__label__sublabel">{item.sublabel}</span>
						{/if}
					</span>
              </a>
            {:else}
              <button on:click={() => {hideDropdown = true; item.action()}} class="avatar__dropdown__item">
                {#if item.icon}
                  <svelte:component this={item.icon} height={16} width={16}/>
                {/if}
                <span class="avatar__dropdown__item__label">
						{item.label}
                  {#if item.sublabel}
							<br/><span class="avatar__dropdown__item__label__sublabel">{item.sublabel}</span>
						{/if}
					</span>
              </button>
            {/if}
          {/each}
        </div>
      </div>
    {:else}
      <Button
        href={browser ? `${import.meta.env.VITE_API_URL}auth/init?url=${window.location.href}` : ''}
        color="brand"
        label="Sign in with GitHub"
        icon={IconGitHub}
      />
    {/if}
  </div>
</header>

<style lang="postcss">
  .header {
    display: flex;
    align-items: center;
    grid-gap: 1rem;
    margin-bottom: 1rem;

    &__actions {
      display: flex;
      margin-left: auto;
      grid-gap: 0.5rem;

      .avatar {
        position: relative;

        &__toggle {
          position: relative;

          &__image {
            width: 2rem;
            border-radius: 100%;
            border: 0.15rem solid transparent;
            transition: border-color 0.2s ease-in-out;
          }

          &::after {
            content: ' ';
            position: absolute;
            bottom: -0.5rem;
            left: 0;
            width: 100%;
            height: 0.5rem;
          }
        }

        &__dropdown {
          visibility: hidden;
          transform: scaleY(0.9);
          opacity: 0;
          transform-origin: top;
          transition: transform 0.1s ease-in-out, opacity 0.1s ease-in-out;
          position: absolute;
          top: calc(100% + 0.1rem);
          width: auto;
          background-color: var(--color-raised-bg);
          border-radius: var(--rounded);
          box-shadow: var(--shadow-floating);
          padding: 0.75rem;
          z-index: 5;
          border: 0.1rem solid var(--color-raised-bg-hover);
          display: flex;
          flex-direction: column;
          grid-gap: 0.25rem;
          right: 0;

          &__item {
            padding: 0.2rem 0.4rem;
            border-radius: var(--rounded-sm);
            display: flex;
            align-items: center;
            grid-gap: 0.3rem;

            &:hover {
              background-color: var(--color-raised-bg-hover);
            }

            &__label {
              min-width: 7.5rem;
              text-align: left;

              &__sublabel {
                color: var(--color-text-lightest);
              }
            }
          }
        }

        &:hover {
          .avatar__toggle {
            &__image {
              border-color: var(--color-brand);
            }
          }
        }

        &:not(.hide-dropdown):hover, &:focus-within, &:focus {
          .avatar__dropdown {
            visibility: visible;
            transform: scaleY(1);
            opacity: 1;
          }
        }
      }
    }
  }
</style>
