// src/routes/[type=projectType]/[identifier]/changelog.svelte
<script lang="ts">
	import Meta from '$components/utils/Meta.svelte'
	import { t } from 'svelte-intl-precompile'
	import { members, project, releaseColors, versions, color } from './_store'
	import { Button, Badge } from 'omorphia'
	import { markdown, formatVersions, downloadUrl, getPrimary } from 'omorphia/utils'
	import IconDownload from 'virtual:icons/heroicons-outline/document-download'
	import IconUpload from 'virtual:icons/heroicons-outline/upload'
	import { browser } from '$app/env'

	const dateFormat = new Intl.DateTimeFormat('en', {
		year: 'numeric',
		month: 'short',
		day: 'numeric',
	})

	let changelogVersions: Array<Version & { duplicate: boolean }>
	$: changelogVersions = $versions.map((version, index) => {
		const nextVersion = $versions[index + 1]
		if (nextVersion && version.changelog && nextVersion.changelog === version.changelog) {
			return { duplicate: true, ...version }
		} else {
			return { duplicate: false, ...version }
		}
	})
</script>

<Meta
	title="{$project.title} - {$t('pages.changelog')}"
	description="Explore the changelog of {$project.title}'s {$versions.length} versions."
	color={$color}
	image={$project?.icon_url} />

<div class="card changelog">
	{#each changelogVersions as version}
		<div class="changelog__item">
			<div
				class="changelog__item__color"
				style:--color="var(--color-badge-{releaseColors[version.version_type]}-dot)"
				class:has-body={version.changelog}
				class:is-duplicate={version.duplicate} />
			<div class="changelog__item__body" style="display:flex; flex:1;">
				<div style="display:flex;">
					<div class="changelog__item__body__title">
						<a href="./version/{version.version_number || version.id}"
							><h1 class="title-secondary">{version.name || version.version_number}</h1></a>
						<a
							href="/user/{$members.find((member) => member.user.id === version.author_id).user
								.username}"
							>{@html $t('generic.byline', {
								values: {
									author: $members.find((member) => member.user.id === version.author_id).user
										.username,
								},
							})}</a>
						&bull;
						<span>{dateFormat.format(new Date(version.date_published))}</span>
					</div>
					<div style="display:flex; flex:1; justify-content:right;">
						{#if browser && document.cookie.indexOf('integration-enabled=true') != -1}
							<div style="width:max-content;margin-right:0.5rem;">
								<Button on:click={(e) => (location.href = 'modrinth:/add-item/' + version.id)}>
									<IconUpload />
									{$t('generic.actions.with_manager')}
								</Button>
							</div>
						{/if}
						<div>
							<Button href={downloadUrl(getPrimary(version.files))}>
								<IconDownload />
							</Button>
						</div>
					</div>
				</div>
				{#if version.changelog && !version.duplicate}
					<div class="changelog__item__body__log text">
						{@html markdown(version.changelog)}
					</div>
				{/if}
			</div>
		</div>
	{/each}
</div>

<style lang="postcss">
	.changelog {
		display: flex;
		flex-direction: column;
		grid-gap: 1rem;

		&__item {
			display: flex;
			grid-gap: 0.8rem;
			position: relative;
			padding-left: 1.8rem;

			&__color {
				--color: var(--color-badge-green-dot);
				left: 0;
				top: 0.5rem;
				width: 0.2rem;
				min-width: 0.2rem;
				position: absolute;
				margin: 0 0.4rem;
				border-radius: var(--rounded-max);
				min-height: 100%;

				&.has-body {
					background-color: var(--color);
				}

				&.is-duplicate {
					height: calc(100% + 1.5rem);
					background: linear-gradient(
						to bottom,
						transparent,
						transparent 30%,
						var(--color) 30%,
						var(--color)
					);
					background-size: 100% 10px;
				}

				&::before {
					content: '';
					width: 1rem;
					height: 1rem;
					background-color: var(--color);
					position: absolute;
					top: 0;
					left: -0.4rem;
					border-radius: var(--rounded-max);
				}
			}

			&__body {
				display: flex;
				flex-direction: column;

				&__title {
					display: flex;
					grid-gap: 0 0.5rem;
					align-items: center;
					flex-wrap: wrap;
				}

				&__log {
					margin-top: 0.5rem;
				}
			}
		}
	}
</style>

// pages/[type]/[id]/changelog.vue
<template>
  <div class="content">
    <Head>
      <Title>
        {{project.title}} - Changelog
      </Title>
      <Meta name="og:title" :content="`${project.title} - Changelog`" />
      <Meta name="description" :content="metaDescription" />
      <Meta name="apple-mobile-web-app-title" :content="`${project.title} - Changelog`" />
      <Meta name="og:description" :content="metaDescription" />
    </Head>
<!--    <VersionFilterControl-->
<!--      class="card"-->
<!--      :versions="versions"-->
<!--      @updateVersions="updateVersions"-->
<!--    />-->
    <div class="card" v-html="versionHtml"></div>
  </div>
</template>
<script>
import DownloadIcon from '~/assets/images/utils/download.svg'
import VersionFilterControl from '~/components/ui/VersionFilterControl'

export default defineNuxtComponent({
  components: {
    VersionFilterControl,
  },
  props: {
    project: {
      type: Object,
      default() {
        return {}
      },
    },
    versions: {
      type: Array,
      default() {
        return []
      },
    },
    members: {
      type: Array,
      default() {
        return []
      },
    },
  },
  data() {
    return {
      filteredVersions: this.versions,
      metaDescription: `View the changelog of ${this.project.title}'s ${this.versions.length} versions.`
    }
  },
  methods: {
    updateVersions(updatedVersions) {
      this.filteredVersions = updatedVersions
    },
  },
  computed: {
    versionHtml() {
      let string = ''

      for (const version of this.filteredVersions) {
        let teamMember = this.members.find((x) => x.user.id === version.author_id)
        //todo: add back download icon and nuxt link.. somehow and highlighting
        string += `
<div class="changelog-item">
  <div class="changelog-bar ${version.version_type} ${ version.duplicate ? 'duplicate' : ''}"></div>
    <div class="version-wrapper">
      <div class="version-header">
        <div class="version-header-text">
          <h2 class="name">
            <a href="/${this.project.project_type}/${this.project.slug ? this.project.slug : this.project.id}/version/${encodeURI(version.displayUrlEnding)}">
              ${version.name}
            </a>
          </h2>
          ${teamMember ? `<span>
            by
            <a
              class="text-link"
              href="${'/user/' + teamMember.user.username}"
            >
              ${teamMember.user.username}
            </a>
          </span>` : ''}
          <span>
            on
            ${this.$dayjs(version.date_published).format('MMM D, YYYY')}
          </span>
        </div>
        <a
          href="${this.$findPrimary(this.project, version).url}"
          class="iconified-button download"
          title="Download ${version.name}"
        >
          Download
        </a>
      </div>
      ${version.changelog && !version.duplicate ? `<div
        class="markdown-body"
      >
        ${this.$xss(this.$md(version.changelog))}
      </div>` : ''}
  </div>
</div>
        `
      }

      return string
    }
  },
  auth: false,
})
</script>

<style lang="scss">
.changelog-item {
  display: block;
  margin-bottom: 1rem;
  position: relative;
  padding-left: 1.8rem;

  .changelog-bar {
    --color: var(--color-special-green);

    &.alpha {
      --color: var(--color-special-red);
    }

    &.release {
      --color: var(--color-special-green);
    }

    &.beta {
      --color: var(--color-special-orange);
    }

    left: 0;
    top: 0.5rem;
    width: 0.2rem;
    min-width: 0.2rem;
    position: absolute;
    margin: 0 0.4rem;
    border-radius: var(--size-rounded-max);
    min-height: 100%;
    background-color: var(--color);

    &:before {
      content: '';
      width: 1rem;
      height: 1rem;
      position: absolute;
      top: 0;
      left: -0.4rem;
      border-radius: var(--size-rounded-max);
      background-color: var(--color);
    }

    &.duplicate {
      background: linear-gradient(
        to bottom,
        transparent,
        transparent 30%,
        var(--color) 30%,
        var(--color)
      );
      background-size: 100% 10px;
    }

    &.duplicate {
      height: calc(100% + 1.5rem);
    }
  }

  .version-header {
    display: flex;
    align-items: center;
    margin-top: 0.2rem;

    .circle {
      min-width: 0.75rem;
      min-height: 0.75rem;
      border-radius: 50%;
      display: inline-block;
      margin-right: 0.25rem;
    }

    .version-header-text {
      display: flex;
      align-items: baseline;
      flex-wrap: wrap;

      h2 {
        margin: 0;
        font-size: var(--font-size-lg);
      }

      h2,
      span {
        padding-right: 0.25rem;
      }
    }

    .download {
      display: none;

      @media screen and (min-width: 800px) {
        display: flex;
      }
    }

    .markdown-body {
      margin: 0.5rem 0.5rem 0 0;
    }
  }
}
</style>
