// components/Badge.vue
<template>
  <span :class="'version-badge ' + color + ' type--' + type">
    <template v-if="color"
      ><span class="circle" /> {{ $capitalizeString(type) }}</template
    >
    <template v-else-if="type === 'admin'"
      ><ModrinthIcon /> Modrinth Team</template
    >
    <template v-else-if="type === 'moderator'"
      ><IconScales /> Moderator</template
    >
    <template v-else-if="type === 'creator'"><IconBox /> Creator</template>
    <template v-else-if="type === 'approved'"><IconList /> Listed</template>
    <template v-else-if="type === 'unlisted'"><IconEyeOff /> Unlisted</template>
    <template v-else-if="type === 'draft'"><IconFileText /> Draft</template>
    <template v-else-if="type === 'archived'"
      ><IconArchive /> Archived</template
    >
    <template v-else-if="type === 'rejected'"><IconCross /> Rejected</template>
    <template v-else-if="type === 'processing'"
      ><IconUpdate /> Under review</template
    >
    <template v-else
      ><span class="circle" /> {{ $capitalizeString(type) }}</template
    >
  </span>
</template>

<script>
import ModrinthIcon from '~/assets/brand/logo.svg?inline'

export default {
  name: 'Badge',
  components: { ModrinthIcon },
  props: {
    type: {
      type: String,
      required: true,
    },
    color: {
      type: String,
      default: '',
    },
  },
}
</script>

<style lang="scss" scoped>
.version-badge {
  display: flex;
  align-items: center;
  font-weight: bold;
  width: fit-content;
  --badge-color: var(--color-special-gray);
  color: var(--badge-color);

  .circle {
    width: 0.5rem;
    height: 0.5rem;
    border-radius: 50%;
    display: inline-block;
    margin-right: 0.25rem;
    background-color: var(--badge-color);
  }

  svg {
    margin-right: 0.25rem;
  }

  &.type--rejected,
  &.red {
    --badge-color: var(--color-special-red);
  }

  &.type--moderator,
  &.type--processing,
  &.orange {
    --badge-color: var(--color-special-orange);
  }

  &.type--admin,
  &.green {
    --badge-color: var(--color-special-green);
  }

  &.type--creator,
  &.type--approved,
  &.blue {
    color: var(--color-special-blue);
  }

  &.type--unlisted,
  &.purple {
    color: var(--color-special-purple);
  }

  &.gray {
    --badge-color: var(--color-special-gray);
  }
}
</style>

// src/components/elements/Badge.svelte
<script lang="ts">
	export let label = '';
	export let color = '';
</script>

<div class="badge badge--color-{color}">
	<span class="badge__label">{label}</span>
</div>

<style lang="postcss">
	.badge {
		font-weight: var(--font-weight-bold);

		&--color-green {
			color: var(--color-badge-green-text);
			--color-dot: var(--color-badge-green-dot);
		}
		&--color-yellow {
			color: var(--color-badge-yellow-text);
			--color-dot: var(--color-badge-yellow-dot);
		}
		&--color-red {
			color: var(--color-badge-red-text);
			--color-dot: var(--color-badge-red-dot);
		}

		&__label::before {
			content: '';
			display: inline-block;
			width: 0.5rem;
			height: 0.5rem;
			border-radius: 50%;
			background-color: var(--color-dot);
			margin-right: 0.5rem;
		}
	}
</style>
